version: '3'
services:
  traefik-acme-converter:
    container_name: traefik-acme-converter
    image: ko4la/traefik-acme-converter
    environment:
      - PROVIDER=acme
      - WEBHOOK_URL=${TRAEFIK_ACME_DISCORD_WH}
      - USER_UID=0
      - USER_GID=0
    volumes:
      - ${DOCKER_ROOT}/traefik/letsencrypt:/traefik/letsencrypt:ro
      - /etc/letsencrypt/live:/app/output
    networks:
      admin-net:
        ipv4_address: 172.20.0.6
